spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.username} # 3
    password: ${mail.password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
